// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0l6OOgVvwk5ZARH33iZnFZOfphKvQw_g',
    appId: '1:1050019802238:android:53559b757531669afdbc2f',
    messagingSenderId: '1050019802238',
    projectId: 'ff-cli-test',
    storageBucket: 'ff-cli-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnCHHLYezOwZ2NT5wlTi_f4e2yDQPqF68',
    appId: '1:1050019802238:ios:5d0381e26f81c6dafdbc2f',
    messagingSenderId: '1050019802238',
    projectId: 'ff-cli-test',
    storageBucket: 'ff-cli-test.appspot.com',
    iosClientId: '1050019802238-a29n2gt1if9pgr1t3rneip1h9hg1s3kt.apps.googleusercontent.com',
    iosBundleId: 'com.example.ffCliTest',
  );
}
